name: iOS Build for Sideloading (Unsigned)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Build LibRyujinx
        run: |
          cd src/LibRyujinx
          dotnet publish -c Release -r ios-arm64

      - name: Build the app (Unsigned)
        run: |
          xcodebuild -workspace src/RyujinxiOS/Ryujinx.xcodeproj/project.xcworkspace \
                     -scheme Ryujinx \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/Ryujinx.xcarchive \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_ENTITLEMENTS="" \
                     CODE_SIGNING_ALLOWED=NO \
                     archive

      - name: Export Unsigned IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Ryujinx.xcarchive \
                     -exportPath $PWD/build \
                     -exportOptionsPlist src/RyujinxiOS/ExportOptions.plist \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_ENTITLEMENTS="" \
                     CODE_SIGNING_ALLOWED=NO

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: Ryujinx-unsigned.ipa
          path: build/Ryujinx.ipa
