name: Build Libraries

on:
  workflow_dispatch:

jobs:
  build-libraries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    # Install dependencies for building libraries
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential wget cmake

    # Create a directory to store all libraries
    - name: Create directory for libraries
      run: mkdir -p libs

    # Build zlib
    - name: Build zlib
      run: |
        wget https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz -O zlib-1.2.11.tar.gz
        tar -xvzf zlib-1.2.11.tar.gz
        cd zlib-1.2.11
        ./configure
        make
        cp libz.so ../libs/libz.so

    # Create stubs for other libraries
    - name: Create stub libraries
      run: |
        echo "void dummy() {}" > dummy.c
        clang -shared -o libs/liblog.so dummy.c
        clang -shared -o libs/libdl.so dummy.c
        clang -shared -o libs/libm.so dummy.c
        clang -shared -o libs/libgcc.so dummy.c
        clang -shared -o libs/libc.so dummy.c

    # Upload compiled libraries as an artifact
    - name: Upload Libraries
      uses: actions/upload-artifact@v3
      with:
        name: compiled-libraries
        path: libs/
