name: iOS Build for Sideloading

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: '3.3' # Not needed with a `.ruby-version` or `.tool-versions`
         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        
      - name: Install dependencies
        run: |
          gem install cocoapods
          pod install --project-directory=src/RyujinxiOS

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Build the app
        run: |
          xcodebuild -workspace src/RyujinxiOS/Ryujinx.xcodeproj/project.xcworkspace \
                     -scheme Ryujinx \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/Ryujinx.xcarchive \
                     archive

      - name: Export IPA
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Ryujinx.xcarchive \
                     -exportPath $PWD/build \
                     -exportOptionsPlist src/RyujinxiOS/ExportOptions.plist

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Ryujinx.ipa
          path: build/Ryujinx.ipa
