name: Build Libraries

on:
  workflow_dispatch: # Manually trigger this workflow

jobs:
  build-libs:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld libc6-dev libgcc-9-dev liblog4cxx-dev zlib1g-dev

      - name: Build Libraries
        run: |
          # Your commands to build the libraries
          # For example:
          mkdir -p libs
          cd your_library_source
          make # or any other build command you use
          cp your_library.so ../libs/

      - name: Upload Libraries as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-libs
          path: libs/
